// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo5mnfM_teV-_LXNy8e1qTxdMc6if5obc',
    appId: '1:678280642684:web:bf2821a8035e10050a09f9',
    messagingSenderId: '678280642684',
    projectId: 'taxitera-3ddad',
    authDomain: 'taxitera-3ddad.firebaseapp.com',
    storageBucket: 'taxitera-3ddad.firebasestorage.app',
    measurementId: 'G-4F8X67GXHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCCHL0OYiVuAvr7fPVPH2NVIx3-ayMIRk',
    appId: '1:678280642684:android:ee862ac60f2cce6d0a09f9',
    messagingSenderId: '678280642684',
    projectId: 'taxitera-3ddad',
    storageBucket: 'taxitera-3ddad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnXCbFbpqmk7ddgb5afh63Zgo1ZjqE3fw',
    appId: '1:678280642684:ios:21164682528ddf4d0a09f9',
    messagingSenderId: '678280642684',
    projectId: 'taxitera-3ddad',
    storageBucket: 'taxitera-3ddad.firebasestorage.app',
    iosBundleId: 'com.example.taxiTera',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnXCbFbpqmk7ddgb5afh63Zgo1ZjqE3fw',
    appId: '1:678280642684:ios:21164682528ddf4d0a09f9',
    messagingSenderId: '678280642684',
    projectId: 'taxitera-3ddad',
    storageBucket: 'taxitera-3ddad.firebasestorage.app',
    iosBundleId: 'com.example.taxiTera',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo5mnfM_teV-_LXNy8e1qTxdMc6if5obc',
    appId: '1:678280642684:web:cf615d3daa90c6440a09f9',
    messagingSenderId: '678280642684',
    projectId: 'taxitera-3ddad',
    authDomain: 'taxitera-3ddad.firebaseapp.com',
    storageBucket: 'taxitera-3ddad.firebasestorage.app',
    measurementId: 'G-XX8RB2T2TM',
  );
}
